export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOAD_ALL_BOOKS = 'LOAD_ALL_BOOKS';
export const BOOKS_AND_MESSAGE = 'BOOKS_AND_MESSAGE';
export const CHANGE_ZIP = 'CHANGE_ZIP';
